### ISSUE TITLE
Error: Expected plugin to either be a plugin instance or a { name, config }

### ISSUE THREAD

**Issue by zapateroremendon** [TransbankDevelopers/transbank-pos-sdk-web-agent#32]
Hola,
Estoy recibiendo este error, luego de ejecutar $npm install, he probado con distintas versiones de node.

An unhandled rejection has occurred inside Forge:
Error: Expected plugin to either be a plugin instance or a { name, config } object but found ["@electron-forge/plugin-webpack",{"loggerPort":9001,"mainConfig":"./webpack.main.config.js","renderer":{"config":"./webpack.renderer.config.js","entryPoints":[{"html":"./src/index.html","js":"./src/renderer.ts","name":"main_window"}]}}]
at /home/local/Downloads/transbank-pos-sdk-web-agent/node_modules/@electron-forge/core/dist/util/plugin-interface.js:32:19
    at Array.map (<anonymous>)
    at new PluginInterface (/home/local/Downloads/transbank-pos-sdk-web-agent/node_modules/@electron-forge/core/dist/util/plugin-interface.js:16:44)
    at exports.default (/home/local/Downloads/transbank-pos-sdk-web-agent/node_modules/@electron-forge/core/dist/util/forge-config.js:158:43)
    at async Task.task (/home/local/Downloads/transbank-pos-sdk-web-agent/node_modules/@electron-forge/core/dist/api/start.js:43:35)
    at async Task.run (/home/local/Downloads/transbank-pos-sdk-web-agent/node_modules/listr2/dist/index.cjs:978:11)
    at async /home/local/Downloads/transbank-pos-sdk-web-agent/node_modules/p-map/index.js:57:22

alguna idea como solucionarlo?

**Comment by mastudillot** [comment]
Hola @zapateroremendon

Nos puedes indicar ¿en qué sistema operativo estás tratando de hacer build?

Y los pasos que realizaste, solo fue clonar el proyecto y hacer el npm install ?

**Comment by zapateroremendon** [comment]
Gracias por su respuesta. Lo estoy compilando en linux(manjaro). Lo solucioné modificando el archivo package.json a :

"plugins": [
        _{
          "name": "@electron-forge/plugin-webpack",
          "config":_ {
            "loggerPort": 9001,
            "mainConfig": "./webpack.main.config.js",
            "renderer": {
              "config": "./webpack.renderer.config.js",
              "entryPoints": [
                {
                  "html": "./src/index.html",
                  "js": "./src/renderer.ts",
                  "name": "main_window"
                }
              ]
            }
          }
        _}_
       ]

además, tuve que bajar las versiones de npm hasta 16.20.1 y luego subir hasta la 20.3.1...

**Comment by mastudillot** [comment]
Gracias por el feedback

**Comment by zapateroremendon** [comment]
Hola, No logro que reconozca la conexion a pos ingenico 3500 con transbank pos sdk web js - example

Lo compile con node 14.21.3, sin aplicar los cambios antes mencionados en este post, me arroja este error:

A JavaScript error occurred in the main process
Uncaught Exception:
Error: The module '/home/user/Downloads/Nodejs/transbank-pos-sdk-web-agent/.webpack/main/native_modules/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 85. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object../node_modules/@serialport/bindings/lib/linux.js (/home/user/Downloads/Nodejs/transbank-pos-sdk-web-agent/.webpack/main/index.js:899:17)
    at __webpack_require__ (/home/user/Downloads/Nodejs/transbank-pos-sdk-web-agent/.webpack/main/index.js:21:30)
webpack built 52983c32e86fa48b822d in 2700ms
Issues checking in progress...
No issues found.

alguna sugerencia?
