### ISSUE TITLE
A JavaScript error occurred different Node.js versions 83/85

### ISSUE THREAD

**Issue by zapateroremendon** [TransbankDevelopers/transbank-pos-sdk-web-agent#33]
Hola, No logro que reconozca la conexion a pos ingenico 3500 con transbank pos sdk web js - example
OS:manjaro

Lo compile con node 14.21.3, no aplique los cambios del post #33, me arroja este error:

A JavaScript error occurred in the main process
Uncaught Exception:
Error: The module '/home/user/Downloads/Nodejs/transbank-pos-sdk-web-agent/.webpack/main/native_modules/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 85. Please try re-compiling or re-installing
the module (for instance, using npm rebuild or npm install).
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object../node_modules/@serialport/bindings/lib/linux.js (/home/user/Downloads/Nodejs/transbank-pos-sdk-web-agent/.webpack/main/index.js:899:17)
at webpack_require (/home/user/Downloads/Nodejs/transbank-pos-sdk-web-agent/.webpack/main/index.js:21:30)
webpack built 52983c32e86fa48b822d in 2700ms
Issues checking in progress...
No issues found.
############################
Intente las sugerencias "(for instance, using npm rebuild or npm install)", sin suerte....
#############################
alguna sugerencia?

**Comment by mastudillot** [comment]
Podrías hacer una instalación limpia? Eso me suena que es porque ya tienes modulos que fueron compilado con otra versión de Node

**Comment by zapateroremendon** [comment]
Gracias por la respuesta, ahora si compila, lo que me funcionó:

1.- bajar la version de python a 3.6.15
2.- luego de #npm install , aplique #./node_modules/.bin/electron-rebuild para transbank-pos-sdk-web-agent 
3.- para transbank-pos-sdk-web-example me funciono sin problemas

sin embargo, el pos me aparece desconectado...debiese conectar en /dev/ttyACM0 , sigo investigando.

![Screenshot_20230707_163651](https://github.com/TransbankDevelopers/transbank-pos-sdk-web-agent/assets/37345629/b139a104-4626-424c-8a9c-567836dbfdfe)

![Screenshot_20230707_163702](https://github.com/TransbankDevelopers/transbank-pos-sdk-web-agent/assets/37345629/67224d06-0016-4403-bd5c-246b942555c2)
